spring:
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:33306/spring_batch
      username: user
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver